version: '3'
services:

  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env.dev
    depends_on:
      - postgres
      - redis
   
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    env_file:
      - ./worker/.env.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis